### ISSUE TITLE
doc directory is becoming a little untidy due to number of different files in a flat structure

### ISSUE THREAD

**Issue by DavidAntliff** [FlowM2M/AwaLWM2M#245]
Might be tidier to put images into a subdirectory, at the very least. That would make the .md files easier to find.

**Comment by TonyWalsworthImg** [comment]
True, but the .md files are designed to be navigated via linkage from the top level rather than searched out individually so it really doesn't matter if the /doc folder is untidy. I can agree with you from a documentation/editing perspective though. I'm happy to move all of the images to a doc/images/ sub folder and then go through the .md files to change the source path for each image. Will take me a couple of hours probably. This obviously won't change the look and feel from the reader's perspective. It's just folder housekeeping.

**Comment by DavidAntliff** [comment]
Ok, if you're happy to do so. If you move the images into a subfolder then ask @seank-img to show you a clever sed trick to scrape the filenames from images/* and pipe through sed to rename the paths internally, it will take only a few seconds, and save you couple of hours :)

**Comment by seank-img** [comment]
Something like...
``` (cd doc; mkdir images; ls -1 *.png | xargs -I '{}' sh -c 'sed -i "s|\({}\)|images/\\1|g" *.md; git mv {} images/{}; git add *.md;') ```

**Comment by DavidAntliff** [comment]
@seank-img yes, that works well, I've put it in a PR - since I raised the issue, only fair I run and verify your fix. Thanks for the correct magical incantation.
