### ISSUE TITLE
Wakama vs Awa

### ISSUE THREAD

**Issue by ekarlso** [FlowM2M/AwaLWM2M#287]
What are the biggest differences between wakaama and Awa?

**Comment by serafimdasaudade** [comment]
Hi,
I used Wakama on a project for a few months. But I moved to AwaLWM2M due to the following reasons.

1 - I think the documentation is better.
2 - The code is easier to read,
3 - It can be compiled into an environment easily contiki.
4 - There are many examples

These are for me the main reasons.

Cumps,

**Comment by torvall** [comment]
Wakaama is (sort of) a LWM2M library that you add to your server and client (and optionally bootstrap server) projects and only provides basic functionality. You have to deal with socket handling, process control, etc. yourself.

AWA, on the other hand, is a set of client, server and bootstrap daemons that take care of all networking and process control out of the box and provide an IPC API with which your client and server applications interface with to do LWM2M operations.

AWA also provides a small footprint client targeted at constrained devices that can be access through a static API.
