### ISSUE TITLE
Static API - server initiated bootstrap

### ISSUE THREAD

**Issue by mkmk88** [FlowM2M/AwaLWM2M#331]
I have a question: how to perform server initiated bootstrap on Contiki? Alternatively, how to re-trigger client initiated bootstrap if the server was restarted? Currently, I only run "AwaStaticClient_Process" in main loop and I don't see any way to register callbacks for handling situation when server is restarted and bootstrap procedure must be repeated.

**Comment by boyvinall** [comment]
Hi @mkmk88, Awa doesn't yet support server-initiated bootstrap.  Interestingly though, some recent discussions on OpenMobileAlliance/OMA_LwM2M_for_Developers#179 are suggesting that this should not be mandated by the spec.  

> Alternatively, how to re-trigger client initiated bootstrap if the server was restarted? 
> handling situation when server is restarted and bootstrap procedure must be repeated

You shouldn't need to re-bootstrap just because the server has been restarted.  The client device will re-register during its regular update interval and should get re-connected at that point.  The register update interval on our cloud-based DeviceServer is set to 60sec, and IMHO this is a good setting.

**Comment by mkmk88** [comment]
Ok, thanks for clarification. Maybe I didn't wait for 1 minute and this was my problem. Cheers.
