### ISSUE TITLE
Content type 11542 support

### ISSUE THREAD

**Issue by cobynano** [FlowM2M/AwaLWM2M#342]
While attempting to run against Leshan, I noticed that the content type 11542 wasn't supported by awa client.  This is a change that was made for LWM2M 1.0 GA release.  Anyone seeing this?

Also, does anyone know what the plans are to integrate changes to support the updated and GA version of the LWM2M 1.0 spec that was released this week?

Thanks
Maya

**Comment by boyvinall** [comment]
Hi @cobynano, most people in Imagination are working only with Awa and our own cloud-based DeviceServer, so we've not yet hit the problem you're seeing.  It's probably fair to say that we've not yet reviewed the changes since the 20160407 version, although clearly this is something that needs to be addressed.  As always, pull requests are gratefully received, so if there's something you're hitting then we'll quickly review any PRs. Otherwise, I think we're likely to start looking at changes in this version within the next few weeks.  As an aside, are you aware of some document that lists the differences in this spec version?  

Specifically on the content-type issue you're seeing here, it should be pretty quick to fix up so we'll probably address it in the next couple of days.

**Comment by boyvinall** [comment]
BTW, we will add support for recognising/deserialising 11542/11543 but we will initially leave the default for any messages sent from clients as 1542. This should allow people some time to update any other devices/infrastructure as needed before we switch the default option for new messages.  It looks like Leshan still allows clients to connect with [`OLD_TLV_CODE`](https://github.com/eclipse/leshan/search?utf8=%E2%9C%93&q=OLD_TLV_CODE+).

**Comment by DavidAntliff** [comment]
@boyvinall when Imagination was an OMA member, I had access to their documents in Word format. This made it easy to do a "diff" (via Word) and see what changes were introduced in each new revision. There was an archive of these files on the SAN. This diff is possible to do with the public PDF versions, although may require a lot more messing around with file formats, depending on how the PDF has been created.

**Comment by boyvinall** [comment]
Thanks @DavidAntliff.  I did previously find a [stash of docs](http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/Permanent_documents/) but was wondering if there was some nice migration guide etc.  Guess we'll have to expend a few more brain cells and keystrokes 😃

**Comment by boyvinall** [comment]
@cobynano I managed to register against the public Leshan server and read/write some objects. When I attempted bootstrap though, I got a "no bootstrap config" 4.00 response back. I've not tried the Leshan bootstrap before, so maybe just something simple I missed there.  Anyway, hopefully this gets you past your hurdle. Shout if it doesn't.
